### ISSUE TITLE
"ERROR: conflicting dependencies, requested rsa==4.7, google-auth 1.11.0 depends on rsa<4.1 and >=3.1.4"

### ISSUE THREAD

**Issue by aSemy** [conorcunningham/google-ddns#10]
Hi there 👋 

Firstly, thanks for making this project, and making it open source! I hope my reporting an issue is helpful.

I received this error when building the docker image:

```
INFO: pip is looking at multiple versions of cachetools to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 6) and rsa==4.7 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested rsa==4.7
    google-auth 1.11.0 depends on rsa<4.1 and >=3.1.4

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
The command '/bin/sh -c pip install --no-cache-dir -r requirements.txt' returned a non-zero code: 1
ERROR: Service 'google-ddns' failed to build : Build failed
```

**Comment by conorcunningham** [comment]
G'day,

You're welcome, and thanks for pointing out the issue. This is a good reminder to test my repo after a Github security pull request.

First, I have updated my requirements.txt file after a complete reinstall of all packages using pip. I tested locally and all went well.

#11 Merged updated requirements file

I don't use the docker functionality myself, but I did have a play with it just now and it runs fine on my local machine. I modified the Dockerfile to include the `config.yaml` and `ddns-api-key.json` files to the Dockerfile's `COPY` command, but remember that you'll have to provide them. I give an example of them on the project's homepage.

With a correct config file and a valid credentials file the docker image ran well and updated my Google DNS A record.

I'm not much a Docker wizard, so please forgive me if I'm stating the obvious, but I successfully ran the image using the following commands:

`docker build -t dns .`
`docker run dns`

For the sake of science, I made a `docker-compose.yml` file

```yml
version: '3'

services:
  ddns:
    image: dns
    volumes:
    - ./config:/ddns
```

and ran with `docker compose up`. 

Please let me know how you get along, and thank you for taking the time to report the issue.

Cheers,

Conor

**Comment by aSemy** [comment]
Thanks! The changes look good except for one thing. I get an error when I build:

```
  => ERROR [3/4] COPY LICENSE gcp_ddns.py requirements.txt config.yaml ddns-api-key.json ./ 
```

You definitely **don't** want to embed a secret API key in the Docker image. I don't think it makes sense to have the example config in the Docker image either.


I prefer using docker-compose to build the image, so I'm using this docker-compose file:

```yaml
version: "3.9"

services:
  google-ddns:
    build:
      context: "."
    container_name: "google-ddns"
    image: "docker.io/conorcunningham/google-ddns"
    volumes: 
        - "./ddns-config.yaml:/ddns/config.yaml"
        - "./.secret.dns-api-key.json:/ddns/ddns-api-key.json"
```

Then `docker-compose up -d` will build (if necessary) and run. To rebuild the image from scratch, run `docker-compose build --no-cache`.

P.S. a minor point but there's a spelling mistake in the repo's tags :) https://github.com/topics/python-dynmaic-dns
